Update not_everybody_can_be_vegan.md
veganhacktivists/animalsupportbot pull request #12
Opened 2021-06-29 16:13 UTC by natalieb11

Provided a response for this bot question as it was previously empty. I covered commonly discussed groups that are not the focus of vegan activists, as well as groups that are the focus of veganism.

2021-06-29 16:36 UTC, cvqluu commented
Thanks for this! I will take a look this week :)

2021-07-01 18:06 UTC, cvqluu requested changes
Hi, first of all thanks for this! This generally looks great. There's only one bit I'd like to discuss:

> Vegans should not impose colonial principles upon indigenous traditions as this is incredibly harmful and oppressive. Those who consume animal products as a part of their cultural activities are not the focus of vegans.

I suppose the main issue I have with just this little bit is the implication that vegan activism is inherently colonial in some way, or that vegan philosophy in general originates solely from the culture of historical colonizers. 

This is obviously a very tricky subject. I'm not exactly sure how to word this in such a way as to avoid this implication.

Other than this bit, this looks pretty much good to go. 

Thanks again so much for doing this!

2021-07-07 00:47 UTC, natalieb11 commented
Hi! 
I’m so sorry, just seeing this now. Yes I agree, I definitely could word that better to be more accurate in terms of what vegan activism actually is. I’ll revise this and send in the new copy ASAP.
Have a nice night! 
Natalie  

> On Jul 1, 2021, at 2:06 PM, Chau ***@***.***> wrote:
> 
> ﻿
> @cvqluu requested changes on this pull request.
> 
> Hi, first of all thanks for this! This generally looks great. There's only one bit I'd like to discuss:
> 
> Vegans should not impose colonial principles upon indigenous traditions as this is incredibly harmful and oppressive. Those who consume animal products as a part of their cultural activities are not the focus of vegans.
> 
> I suppose the main issue I have with just this little bit is the implication that vegan activism is inherently colonial in some way, or that vegan philosophy in general originates solely from the culture of historical colonizers.
> 
> This is obviously a very tricky subject. I'm not exactly sure how to word this in such a way as to avoid this implication.
> 
> Other than this bit, this looks pretty much good to go.
> 
> Thanks again so much for doing this!
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-10 14:20 UTC, natalieb11 commented
People who can go vegan, should, but who exactly does this include? First, let’s talk about who this typically doesn’t include. 

It is important to recognize that for financial or other personal reasons, not everyone has the freedom to go vegan. For example, if someone is without housing or is in a poor socio-economic condition, it is completely understandable that their focus is on supporting themselves. This is not to say that individuals in these conditions cannot go vegan if they so desire, but these individuals are not the focus of vegan activism. In order to fight for the liberation of animals, we must first be able to keep ourselves supported, and individuals who need to consume animals products out of necessity are not to be blamed for doing so. 

As well, for many indigenous communities, hunting or fishing is an important cultural commitment. Although vegans would argue that killing an animal is never truly ethical, it is very important to recognize the difference between traditional practices and factory farming. **Seeing as the main goal of veganism is to end the exploitation of animals as much as possible, factory farming and widespread use of animal products is the target of vegan activism, as opposed to small scale community hunting and fishing.** Those who consume animal products as a part of their cultural activities are not the focus of vegans.

There is also the topic of illness as a barrier to veganism. Although there are no medical conditions known to make veganism impossible, certain illnesses or differences in ability may make veganism difficult for some individuals. For those who have medical conditions where this is applicable, they are not the focus of vegan activists. It is important to note that you should always check with a medical professional regarding nutritional concerns as they can give you specific guidance for your needs. 

Now that we have covered some of the most common groups that are not the focus of vegans, let’s talk about who should go vegan. If you do not fall into those prior categories and are buying animal products, you should go vegan. If you have the power to choose between a veggie burger and a beef burger, why not choose the ethical option? If you have the means to educate yourself on animal welfare issues, and the power to change your contributions to these issues, you should go vegan. From animal welfare to human welfare, the environment and your health, there are many advantages to going vegan. In many regards, a vegan diet can be less expensive and healthier than an omnivorous diet. Foods such as legumes and rice are very inexpensive and easy to access and prepare. Especially with the expansive list of mock animal products, you do not even need to worry about missing out on your favourite meals. There is such a variety of vegan options to choose from, you just need to do the research. Although there are barriers to veganism, the more individuals that go vegan, the easier it will become for those who currently cannot do so.

2021-07-18 22:40 UTC, cvqluu commented
Thanks! Looks good to me. Will merge now

2021-07-18 22:40 UTC, merged